# Generated by Django 4.1.4 on 2023-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/thumbnails/"
            ),
        ),
    ]
